theme: jekyll-theme-dinky
title: SMT-COMP
description: The International Satisfiability Modulo Theories (SMT) Competition.
collections:
    main-benchmarks:
        output: true
    participants:
        output: true
    news:
        output: true
    organizers:
        output: true
    results:
        output: false
