theme: jekyll-theme-dinky
title: SMT-COMP
description: The International Satisfiability Modulo Theories (SMT) Competition.
collections:
    benchmarks:
        output: true
    participants:
        output: true
    results:
        output: false
    news:
        output: true
    single-results:
        output: true
    incremental-results:
        output: true
    unsatcore-results:
        output: true
    challenge-results:
        output: true
