theme: jekyll-theme-dinky
title: SMT-COMP
description: The International Satisfiability Modulo Theories (SMT) Competition.
collections:
    benchmarks:
        output: true
    participants:
        output: true
    participants_split:
        output: true
    results:
        output: false
    news:
        output: true
    single-results:
        output: true
    incremental-results:
        output: true
    unsat_core-results:
        output: true
    single_query_challenge-results:
        output: true
    incremental_challenge-results:
        output: true
    model_validation-results:
        output: true
